name = "cdm-suite"
compatibility_date = "2025-11-16"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "cdm-suite-db"
database_id = "c444f762-3812-4b8b-9c62-fed9f47fc8c7"

[[r2_buckets]]
binding = "R2"
bucket_name = "cdm-suite-assets"

[observability]
enabled = true
